### ISSUE TITLE
Infusions, WeaponNames and WeaponTypes

### ISSUE THREAD

**Issue by tzbob** [Pireax/DS3ParamExtractor#2]
The Google Docs Sheet[1] has Infusions, WeaponNames and WeaponTypes. Can you extract these from the .param files or are they manually generated? Feel free to close this issue if it doesn't apply.

[1] : https://docs.google.com/spreadsheets/d/1dw2rIaT44R708h4m_BBSkK9GGoCog0V8xowZbyAxUIM/

**Comment by ttilley** [comment]
I can't speak for @Pireax but I know a lot of that information has already existed from mining memory and playing around with cheat engine. I would not be amazed if the infusion numbers were taken directly from this post: http://forum.cheatengine.org/viewtopic.php?p=5662748#5662748

**Comment by Pireax** [comment]
Infusions and WeaponTypes were manually made, WeaponNames are from http://pastebin.com/NYibM464 (I think this is in the link you posted).

**Comment by ttilley** [comment]
the weapon name generator script for cheat engine is here: http://forum.cheatengine.org/viewtopic.php?p=5662606#5662606

...but it hasn't worked since initial release and hasn't been updated. probably something to look into when DLC is released if there isn't an easier list in a data file somewhere.

**Comment by Pireax** [comment]
I have almost implemented everything necessary to generate names, I just want to add protobuf support before commiting.

**Comment by Pireax** [comment]
Support for .fmg files is now in the master branch, these files contain data such as weapon names, descriptions, etc. These .fmg files can be found in DSIII/Data1/msg/*.msgbnd.
